version: 2.1
orbs:
  node: circleci/node@1.1.6
executors:
  docker-node:
    docker:
      - image: circleci/node:14.15.1
workflows:
  main:
    jobs:
      - prepare
      - testing:
          requires:
            - prepare
      - build:
          requires:
            - prepare
      - deployments:
          requires:
            - testing
            - build
          filters:
            branches:
              only:
                - main
jobs:
  prepare:
    executor: docker-node
    working_directory: ~/repo
    description: "Download and cache dependencies"
    steps:
      - checkout
      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}
      - run:
          name: Install Dependencies
          command: yarn install
      - save_cache:
          name: Save Yarn Package Cache
          paths:
            - node_modules
            - ~/.cache/yarn
          key: yarn-packages-{{ checksum "yarn.lock" }}
      - persist_to_workspace:
          root: ~/repo
          paths:
            - node_modules
  testing:
    executor: docker-node
    working_directory: ~/repo
    description: "Run unit tests and collect coverage reports"
    steps:
      - checkout
      - attach_workspace:
          at: ~/repo
      - run:
          name: "Unit tests and coverage"
          command: CI=true yarn test
  build:
    executor: docker-node
    working_directory: ~/repo
    description: "Build the web app"
    steps:
      - checkout
      - attach_workspace:
          at: ~/repo
      - run:
          name: "Build the web app"
          command: yarn build
      - persist_to_workspace:
          root: ~/repo
          paths:
            - build
  deployments:
    executor: docker-node
    working_directory: ~/repo
    description: "Deploy built web app with Surge"
    steps:
      - checkout
      - attach_workspace:
          at: ~/repo
      - run:
          name: "Deploy built web app with Surge"
          command: yarn deploy --domain https://messages.surge.sh
