version: 2.1
orbs:
  node: circleci/node@1.1.6
workflows:
  main:
    jobs:
      - prepare
      - test:
          requires:
            - prepare
      - build:
          requires:
            - prepare
      - deployments:
          requires:
            - test
            - build
jobs:
  prepare:
    docker:
      - image: circleci/node:14.12.0
    working_directory: ~/repo
    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}
      - run:
          name: Install Dependencies
          command: yarn install
      - save_cache:
          name: Save Yarn Package Cache
          paths:
            - node_modules
            - ~/.cache/yarn
          key: yarn-packages-{{ checksum "yarn.lock" }}
      - persist_to_workspace:
          root: ~/repo
          paths:
            - node_modules
  test:
    docker:
      - image: circleci/node:14.12.0
    working_directory: ~/repo
    steps:
      - checkout
      - attach_workspace:
          at: ~/repo
      - run:
          name: "Unit tests and coverage"
          command: CI=true yarn test
      - persist_to_workspace:
          root: ~/repo
          paths:
            - node_modules
  build:
    docker:
      - image: circleci/node:14.12.0
    working_directory: ~/repo
    steps:
      - checkout
      - attach_workspace:
          at: ~/repo
      - run:
          name: "Build the web app"
          command: yarn build
      - persist_to_workspace:
          root: ~/repo
          paths:
            - node_modules
  deployments:
    docker:
      - image: circleci/node:14.12.0
    working_directory: ~/repo
    steps:
      - checkout
      - attach_workspace:
          at: ~/repo
      - run:
          name: "Deploy built web app with Surge"
          command: yarn deploy --domain https://messages.surge.sh
          branches:
            only:
              - master
      - persist_to_workspace:
          root: ~/repo
          paths:
            - node_modules