export enum messagesActionTypes {
  INIT = '@@INIT',
  REQUEST_MESSAGES = 'REQUEST_MESSAGES',
  REQUEST_MESSAGES_SUCCESS = 'REQUEST_MESSAGES_SUCCESS',
  REQUEST_MESSAGES_FAILURE = 'REQUEST_MESSAGES_FAILURE',
}
