export enum messagesActionTypes {
  INIT = '@@INIT',
  REQUEST_MESSAGES = 'REQUEST_MESSAGES',
  REQUEST_MESSAGES_SUCCESS = 'REQUEST_MESSAGES_SUCCESS',
  REQUEST_MESSAGES_FAILURE = 'REQUEST_MESSAGES_FAILURE',
  SEND_MESSAGE = 'SEND_MESSAGE',
  SEND_MESSAGE_SUCCESS = 'SEND_MESSAGE_SUCCESS',
}
